config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  namespace :api do
    resources :nearby, only: :index
  end

  namespace :dashboard do
    resources :places
  end
  
  resources :places
  resources :relocations, only: :index
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, :full_address, :latitude, :longitude, presence: true
  reverse_geocoded_by :latitude, :longitude, :address => :geocode_address
  after_validation :reverse_geocode

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  has_many :places

  validates :username,
    :uniqueness => {
      :case_sensitive => false
    },
    :format => { with: /\A[a-z0-9]+\Z/ }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end    
end

app/controllers/api/nearby_controller.rb
class Api::NearbyController < ApplicationController
  layout false

  def index
    @nearbys = Place.near([params[:lat], params[:lon]],100) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :full_controller_name  

  def full_controller_name
    self.class.name.underscore.gsub('_controller', '').gsub('/', ' ')
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/dashboard/places_controller.rb
class Dashboard::PlacesController < ApplicationController
  before_action :authenticate_user!

  def index
    @places = current_user.places.all
  end

  def show
    @place = current_user.places.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.new(place_params)
    if @place.save
      redirect_to dashboard_places_path
    else
      render :new
    end
  end

  def edit
    @place = current_user.places.find(params[:id])
  end

  def update
    @place = current_user.places.find(params[:id])

    if @place.update(place_params)
      redirect_to dashboard_places_path
    else
      :edit
    end
  end

  def destroy
    @place = current_user.places.find(params[:id])
    @place.destroy

    redirect_to dashboard_places_path
  end

  private
  def place_params
    params.require(:place).permit(:name, :full_address, :latitude, :longitude)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end

end

app/controllers/relocations_controller.rb
class RelocationsController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def javascript_initializer
    controller = full_controller_name.gsub(' ', '.')
    action = action_name

    root = "window.project"
    init_root = "#{root}.init();\n"

    init_controller = "if(#{root}.#{controller}) { \n"
    init_controller += "\tif(#{root}.#{controller}.init) { #{root}.#{controller}.init(); }\n"
    init_controller += "\tif(#{root}.#{controller}.init_#{action_name}) { #{root}.#{controller}.init_#{action_name}(); }\n"
    init_controller += "}"

    init_root + init_controller
  end
end

app/helpers/dashboard/places_helper.rb
module Dashboard::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/dashboard/places/_form.html.slim
.row
  .large-6.columns
    #map-canvas style="height:500px"

  .large-6.columns
    = form_for [:dashboard, @place] do |f|

      - if @place.errors.any?
        #error_explanation
          h2
            = pluralize(@place.errors.count, "error") 
            | prohibited this place from being saved:
          
          ul
            - @place.errors.full_messages.each do |msg|
              li = msg

      p
        = f.label :name
        = f.text_field :name

      p
        = f.label :full_address
        = f.text_area :full_address

      p
        = f.label :latitude
        = f.text_field :latitude

      p
        = f.label :longitude
        = f.text_field :longitude

      p
        button type="submit" Submit
        | &nbsp;
        button#reset-position Reset Position


    p = link_to 'Back', dashboard_places_path

app/views/dashboard/places/edit.html.erb
<h1>Edit Place</h1>

<%= render 'form' %>

app/views/dashboard/places/index.html.slim
h1 My Places

p = link_to "Add Place", new_dashboard_place_path

table cellpadding="6"
  - @places.each do |place|
    tr
      td = place.name
      td = link_to "View", dashboard_place_path(place)
      td = link_to "Edit", edit_dashboard_place_path(place)
      td = link_to "Delete", dashboard_place_path(place), method: :delete, data: { confirm: 'Are you sure ?' }

app/views/dashboard/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

app/views/dashboard/places/show.html.erb
<h1><%= @place.name %></h1>
<p><%= @place.full_address %></p>

<style>
#map-canvas { 
  float: left;
  margin-right: 20px;
  width: 500px;
  height: 600px; 
}
</style>

<div id="map-canvas"></div>

<h2>Nearby Places from Your Location</h2>
<ul>
<% @place.nearbys(100, units: :km).each do |place| %>
  <li><%= link_to place.name, place_path(place) %> (<%= place.distance.round(2) %> km)</li>
<% end %>
</ul>

<p><%= link_to 'Back', places_path %></p>

<script>
function showMarker(position, title) {
  marker = new google.maps.Marker({
    position: position,
    map: map,
    draggable: true,
    title: title
  });

  map.setCenter(position);

  google.maps.event.addListener(marker, 'dragend', function() {
    marker.setMap(null);
    getAddress(marker.getPosition().lat(), marker.getPosition().lng());
  });
}

function reinitialize() {
  position = new google.maps.LatLng(<%= @place.latitude %>, <%= @place.longitude %>);
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  showMarker(position, 'Current Address');
}

loadScript = function() {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&' +
    'callback=reinitialize';
    
  document.body.appendChild(script);
}

$(document).ready(loadScript);
</script>

app/views/home/index.html.erb
<style>
  #map-canvas { height: 400px; }
</style>

LATITUDE = <span id="latitude"latitude></span><br/>
LONGITUDE = <span id="longitude"></span><br/>
ADDRESS = <span id="address"></span>
<span id="change-address">
  <a href="<%= relocations_path %>">Change Address</a>
</span>

<h2>Nearby</h2>
<div id="nearby-container"></div>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&language=id&region=id" type="text/javascript"
    = csrf_meta_tag

  body
    nav.top-bar data-topbar="" 
      ul.title-area
        li.name
          h1 = link_to "Berobat Di Mana", root_path
        li.toggle-topbar.menu-icon
          a href="#" 
            span menu
      section.top-bar-section
        ul.right
          - if user_signed_in?
            li.divider
            li.has-dropdown
              a href="#" Welcome
              ul.dropdown
                li
                  label Dashboard
                li = link_to "My Places", dashboard_places_path
                li.divider
                li
                  label Settings
                li = link_to "Profile", edit_user_registration_path
                li = link_to "Change Password", edit_user_password_path
            li.divider
            li = link_to 'Logout', destroy_user_session_path, method: :delete
          
          - else
            li.divider
            li = link_to 'Register', new_user_registration_path
            li.divider
            li = link_to 'Login', new_user_session_path

    .row
      == yield

    footer.row
      .large-12.columns
        hr/
        .row
          .large-6.columns
            p &copy; Copyright no one at all. Go to town.
          .large-6.small-12.columns
            ul.inline-list.right
              li
                a href="#"  Link 1
              li
                a href="#"  Link 2
              li
                a href="#"  Link 3
              li
                a href="#"  Link 4

    = javascript_include_tag "application"

    script type='text/javascript'
      = javascript_initializer

app/views/places/index.html.erb
<%= link_to 'Add New Place', new_place_path %>

<table cellpadding="6">
  <% @places.each do |place| %>
    <tr>
      <td><%= place.name %></td>
      <td><%= link_to 'Show', place_path(place) %></td>
      <td><%= link_to 'Edit', edit_place_path(place) %></td>
      <td><%= link_to 'Delete', place_path(place), method: :delete, data: { confirm: 'Are you sure' } %></td>
    </tr>
  <% end %>
</table>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>
<p><%= @place.full_address %></p>

<style>
#map-canvas { 
  float: left;
  margin-right: 20px;
  width: 500px;
  height: 600px; 
}
</style>

<div id="map-canvas"></div>

<h2>Nearby</h2>
<ul>
<% @place.nearbys(100, units: :km).each do |place| %>
  <li><%= link_to place.name, place_path(place) %> (<%= place.distance.round(2) %> km)</li>
<% end %>
</ul>

<p><%= link_to 'Back', places_path %></p>

<script>
var map;
var marker;
var mapOptions = {
  zoom: 18
};

function showMarker(position, title) {
  marker = new google.maps.Marker({
    position: position,
    map: map,
    draggable: true,
    title: title
  });

  map.setCenter(position);

  google.maps.event.addListener(marker, 'dragend', function() {
    marker.setMap(null);
    getAddress(marker.getPosition().lat(), marker.getPosition().lng());
  });
}

function reinitialize() {
  position = new google.maps.LatLng(<%= @place.latitude %>, <%= @place.longitude %>);
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  showMarker(position, 'Current Address');
}

loadScript = function() {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&' +
    'callback=reinitialize';
    
  document.body.appendChild(script);
}

$(document).ready(loadScript);
</script>

app/views/relocations/index.html.slim
h1 Change Address

input#map-address name="map-address" type="text"
button#map-button-find Find Me
span#latitude
span#longitude
#address
#map-canvas style="height:500px"